name: zoom_widget
description: Widget to zoom on a canvas of modifiable size that a child widget can hold.
version: 2.1.0
homepage: https://github.com/semakers

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
